"""
Alerts Router - Drift alerts and notification endpoints

Endpoints:
- GET /alerts/{email} - Get active alerts for user
- POST /alerts/check - Run drift check (admin/cron)
- PUT /alerts/{alert_id}/dismiss - Dismiss an alert
"""
from fastapi import APIRouter, Depends, HTTPException
from sqlalchemy.orm import Session
from datetime import datetime, timedelta
from typing import Optional
import models
from database import get_db
from db_utils import get_user
from services.drift_detection import DriftDetector, run_drift_check

router = APIRouter(prefix="/alerts", tags=["Alerts"])



@router.get("/{email}")
def get_user_alerts(
    email: str,
    include_dismissed: bool = False,
    limit: int = 10,
    db: Session = Depends(get_db)
):
    """
    Get active drift alerts for a user

    Returns alerts generated by the drift detection system:
    - No check-in alerts
    - Focus drop alerts
    - Commitment crash alerts
    - High discrepancy alerts
    """
    user = get_user(email, db)

    # Get drift alerts from AgentAdvice
    query = db.query(models.AgentAdvice).filter(
        models.AgentAdvice.user_id == user.id,
        models.AgentAdvice.interaction_type == "drift_alert"
    )

    # Filter to recent alerts (last 7 days)
    query = query.filter(
        models.AgentAdvice.created_at >= datetime.utcnow() - timedelta(days=7)
    )

    alerts = query.order_by(models.AgentAdvice.created_at.desc()).limit(limit).all()

    return {
        "count": len(alerts),
        "alerts": [
            {
                "id": a.id,
                "agent": a.agent_name,
                "title": a.advice.split(":")[0] if ":" in a.advice else "Alert",
                "message": a.advice.split(":")[-1].strip() if ":" in a.advice else a.advice,
                "severity": a.evidence.get("severity", "medium") if a.evidence else "medium",
                "alert_type": a.evidence.get("alert_type") if a.evidence else None,
                "action": a.evidence.get("action") if a.evidence else None,
                "created_at": a.created_at.isoformat(),
                "dismissed": a.followed == False
            }
            for a in alerts
        ]
    }


@router.get("/{email}/count")
def get_alert_count(email: str, db: Session = Depends(get_db)):
    """Get count of active alerts for badge display"""
    user = get_user(email, db)

    count = db.query(models.AgentAdvice).filter(
        models.AgentAdvice.user_id == user.id,
        models.AgentAdvice.interaction_type == "drift_alert",
        models.AgentAdvice.created_at >= datetime.utcnow() - timedelta(days=7),
        models.AgentAdvice.followed != False  # Not dismissed
    ).count()

    return {"count": count, "has_alerts": count > 0}


@router.put("/{alert_id}/dismiss")
def dismiss_alert(alert_id: int, db: Session = Depends(get_db)):
    """Dismiss a specific alert"""
    alert = db.query(models.AgentAdvice).filter(
        models.AgentAdvice.id == alert_id,
        models.AgentAdvice.interaction_type == "drift_alert"
    ).first()

    if not alert:
        raise HTTPException(status_code=404, detail="Alert not found")

    alert.followed = False  # Using followed=False to mark as dismissed
    db.commit()

    return {"dismissed": True, "id": alert_id}


@router.post("/check")
def trigger_drift_check(db: Session = Depends(get_db)):
    """
    Run drift check for all users

    This should be called by a cron job or scheduled task.
    Generates alerts for users who show drift patterns.
    """
    result = run_drift_check(db)
    return result


@router.get("/{email}/drift-status")
def get_drift_status(email: str, db: Session = Depends(get_db)):
    """
    Get comprehensive drift status for a user

    Returns summary of all drift indicators:
    - Days since last check-in
    - Recent completion rate
    - Focus score trend
    - Overall drift risk level
    """
    user = get_user(email, db)

    # Days since last check-in
    last_checkin = db.query(models.CheckIn).filter(
        models.CheckIn.user_id == user.id
    ).order_by(models.CheckIn.timestamp.desc()).first()

    days_since_checkin = 0
    if last_checkin:
        days_since_checkin = (datetime.utcnow() - last_checkin.timestamp).days

    # Recent completion rate
    recent_checkins = db.query(models.CheckIn).filter(
        models.CheckIn.user_id == user.id,
        models.CheckIn.timestamp >= datetime.utcnow() - timedelta(days=7)
    ).all()

    completion_rate = 0
    if recent_checkins:
        completed = sum(1 for c in recent_checkins if c.shipped)
        completion_rate = int((completed / len(recent_checkins)) * 100)

    # Latest shadow data
    shadow = db.query(models.ShadowData).filter(
        models.ShadowData.user_id == user.id
    ).order_by(models.ShadowData.submission_date.desc()).first()

    focus_score = shadow.focus_score if shadow else None
    discrepancy = shadow.discrepancy_score if shadow else None

    # Calculate overall risk level
    risk_score = 0
    risk_factors = []

    if days_since_checkin >= 3:
        risk_score += 30
        risk_factors.append(f"No check-in for {days_since_checkin} days")

    if completion_rate < 50:
        risk_score += 25
        risk_factors.append(f"Low completion rate: {completion_rate}%")

    if focus_score and focus_score < 40:
        risk_score += 20
        risk_factors.append(f"Scattered focus: {int(focus_score)}/100")

    if discrepancy and discrepancy >= 70:
        risk_score += 25
        risk_factors.append(f"High reality gap: {int(discrepancy)}%")

    # Determine risk level
    if risk_score >= 60:
        risk_level = "critical"
    elif risk_score >= 40:
        risk_level = "high"
    elif risk_score >= 20:
        risk_level = "medium"
    else:
        risk_level = "low"

    return {
        "days_since_checkin": days_since_checkin,
        "completion_rate": completion_rate,
        "focus_score": int(focus_score) if focus_score else None,
        "discrepancy_score": int(discrepancy) if discrepancy else None,
        "risk_level": risk_level,
        "risk_score": risk_score,
        "risk_factors": risk_factors
    }
